### ISSUE TITLE
[icebox] Investigate rolling PEG parser for Textmate scope selectors in WASM format

### ISSUE THREAD

**Issue by zm-cttae** [vsce-toolroom/vscode-textmate-languageservice#18]
## ⚡️️ Feature Request

- [x] I'm using the latest version of `vscode-textmate-languageservice` available.
- [x] I searched [existing issues][vsctmls-issues], open & closed. Yes, my feature request is new.

### Is your feature request related to a problem?

The Textmate scope selector shows below-par performance due to exponential expense in `path` in grammar specification.

### Describe the solution you'd like

- [ ] Port PEG parser to Rust using `pest` (`rust-peg`).
- [ ] Build parser using Rust toolchain for WASM generation.
- [ ] Confirm WASM code & bindings works vs [specification](https://github.com/vsce-toolroom/vscode-textmate-languageservice/blob/v1.1.0/test/data/selectors/selector.json#L1-L73) with no regressions.

### Describe alternatives you've considered

Already written `FastScopeSelector` for `scope` & `path` in linear time `O(cN)`
`c` = the number of alphanumeric  scope `atoms`.

[vsctmls-issues]: https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/issues/?sort=created_date&state=opened

**Comment by zm-cttae** [comment]
https://pest.rs/

PEG grammar in Rust

```
space = _{ " " | "\t" }
string = @{ ASCII_ALPHANUMERIC | "_" | "+" }
segment = @{ ( string ~ (string | "-")* | "*") }
atom = { space* ~ segment ~ space* }
scope = { atom ~ ( "." ~ atom )* }
prefix = { "L" | "R" | "B" }
path = { (prefix ~ ":")? ~ scope ~ (space* ~ scope)* }
group = { (prefix ~ ":")? ~ "(" ~ space* ~ selector ~ space* ~ ")" }
negation = { "-" }
expression = { (negation ~ group) | (negation ~ path) | group | path }
operator = { "|" | "&" | "-" }
composite = { (expression ~ space* ~ operator ~ space* ~ composite) | expression }
selector = { (composite ~ space* ~ "," ~ space* ~ selector?) | composite }
start = { selector }
```

**Comment by zm-cttae** [comment]
Optimised Pest parser:

```pest
WHITESPACE          = _{ " " | "\t" }

atom                = { !("-") ~ (ASCII_ALPHANUMERIC | "+" | "_" | "-")+ }
asterisk            = { "*" }
segment             = { atom | asterisk }

scope               = { segment ~ ("." ~ segment)* }

prefix              = { "L" | "R" | "B" }

path                = { (prefix ~ ":")? ~ scope ~ (WHITESPACE+ ~ scope)* }
group               = { (prefix ~ ":")? ~ "(" ~ selector ~ ")" }

MINUS_OPERATOR      = { "-" }
expression          = { MINUS_OPERATOR? ~ (group | path) }

COMPOSITE_OPERATOR  = { "|" | "&" | "-" }

composite           = { expression ~ (COMPOSITE_OPERATOR ~ composite)? }
selector            = { composite ~ ("," ~ selector)? }

start               = { selector }
```

Let's try rust-peg first though..

**Comment by zm-cttae** [comment]
Cost saving is 10-40% using rust-peg compiled to WASM. This isn't good enough to justify switching.

**Comment by zm-cttae** [comment]
With actual disposal using `WasmScopeSelector.free`, times go from $60ns/iter$ to $7.9ns/iter$.
This represents a perf gain of 57% from $29.8ns/iter$ in the original `FirstMateSelector`.
