### ISSUE TITLE
Add API-style methods `getScopeInformationAtPosition` & `getScopeRangeAtPosition`

### ISSUE THREAD

**Issue by zm-cttae** [vsce-toolroom/vscode-textmate-languageservice#22]
## ⚡️️ Feature Request

- [x] I'm using the latest version of `vscode-textmate-languageservice` available.
- [x] I searched [existing issues][vsctmls-issues], open & closed. Yes, my feature request is new.

### Is your feature request related to a problem?

- **As a:** VS Code extension developer,
- **I want to:** get scope information for a specific Textmate grammar
- **So that:** I can consume token data within my extension in a performant manner - [⦿**microsoft/vscode#99356**](https://github.com/microsoft/vscode/issues/99356)

### Describe the solution you'd like

- [x] ✨ Implement a static extension contribution registry that can fallback to `vscode.extensions.all`.
- [x] ✨ Add Textmate grammar resolver methods that can map contributions to their source extensions.

Tasks for the new maintainer [`@zm-cttae`](https://github.com/zm-cttae):
- [x] ✨ Wire the contribution registry to the `TextmateLanguageService` API constructor.
- [x] 🧪 Add automated tests for TypeScript token services from both browser & frontend.
- [x] Add `getTokenInformationAtPosition` method to main API for polyfill - `vscode.TokenInformation`.
- [x] Add `getScopeInformationAtPosition` method to get Textmate token data - `TextmateToken`.
- [x] Add `getScopeRangeAtPosition` method to get token range - `vscode.Range`.
- [x] Add simple function tests for the 3 API methods, and simple performance test.

NB: that we need to reverse sort data when computing active grammar or language definition.

### Describe alternatives you've considered

Still rely on `vscode.ExtensionContext` but we want to make that optional!

[vsctmls-issues]: https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/issues/?sort=created_date&state=opened
